#![doc(hidden)]

///
/// This file was fully generated by GPT-Codex-5.3
/// Please submit improvements if you have ideas
///
use std::io::IsTerminal;

const BOLD: &str = "\x1b[1m";
const UNDERLINE: &str = "\x1b[4m";
const CYAN: &str = "\x1b[36m";
const GREEN: &str = "\x1b[32m";
const RESET: &str = "\x1b[0m";
const OPTION_COL_WIDTH: usize = 28;
const OPTION_DESC_INDENT: &str = "                              ";

pub(crate) fn print_help() {
    if should_style() {
        println!("{BOLD}{CYAN}jao - discover, inspect, and run workspace scripts{RESET}");
        line("  Finds platform scripts recursively and executes them from their own directory.");
        println!();
        section("USAGE");
        line("  jao --list");
        line("  jao --ci --list");
        line("  jao --fingerprint <SCRIPT_COMMAND>...");
        line("  jao <SCRIPT_COMMAND>...");
        #[cfg(feature = "trust-manifest")]
        line("  jao --ci --require-fingerprint <FINGERPRINT> <SCRIPT_COMMAND>...");
        #[cfg(not(feature = "trust-manifest"))]
        line("  jao --require-fingerprint <FINGERPRINT> <SCRIPT_COMMAND>...");
        println!();

        section("OPTIONS");
        option("  -h, --help", "Show this help screen");
        option("      --list", "List runnable scripts as command names plus their resolved file paths");
        option(
            "      --fingerprint <SCRIPT_COMMAND>...",
            "Resolve a script command, then print SHA-256 of canonical path + file contents",
        );
        option("      --ci", "Enable CI mode (non-interactive, no config/manifest I/O)");
        option(
            "      --require-fingerprint <FINGERPRINT>",
            "Require exact script fingerprint before running",
        );
        option("  -V, --version", "Print version");
        println!();

        section("SCRIPT COMMAND INPUT");
        line("  Script file stems still use '.' as command separators.");
        line("  Directories contribute command parts only when they contain a .jaofolder marker.");
        line("  Example: myapp/backend/scripts/build.sh becomes:");
        line("    jao myapp backend build from the workspace root if myapp/ and backend/ are marked");
        line("    jao backend build from inside myapp/");
        line("    jao build from inside backend/");
        line("  Matching extension is chosen by OS: .sh on Unix-like systems, .bat on Windows.");
        line("  The script runs with working directory set to the script's folder.");
        println!();

        section("TRUST BEHAVIOR");
        #[cfg(feature = "trust-manifest")]
        {
            line("  Running a script requires trust.");
            line("  Unknown scripts prompt: trust and run? [y/N]");
            line("  Modified scripts prompt: re-trust and run? [y/N]");
            line("  In non-interactive mode, unknown/modified scripts fail.");
            line("  --list prints trust state labels plus command names and resolved paths.");
            line("  --require-fingerprint can be used in CI mode.");
        }
        #[cfg(not(feature = "trust-manifest"))]
        {
            line("  This build has trust-manifest disabled.");
            line("  All runs require --require-fingerprint <FINGERPRINT>.");
            line("  Runs are always non-interactive and never write trust state.");
            line("  --list prints command names and resolved paths.");
        }
        line("  --ci skips config/manifest creation and never prompts.");
        #[cfg(feature = "trust-manifest")]
        line("  --ci run requires --require-fingerprint <FINGERPRINT>.");
        #[cfg(not(feature = "trust-manifest"))]
        line("  --ci uses the same fingerprint-required run policy.");
        line("  --ci --list prints command names and resolved paths (no trust labels).");
        println!();

        section("EXAMPLES");
        example("  jao --fingerprint deploy api prod");
        line("    Resolve deploy.api.prod.sh/.bat, then fingerprint that script file.");
        example("  jao --list");
        #[cfg(feature = "trust-manifest")]
        line("    Output format: <trust-state> <script-command> -> <script-path>.");
        #[cfg(not(feature = "trust-manifest"))]
        line("    Output format: <script-command> -> <script-path>.");
        example("  jao --ci --list");
        line("    Output format: <script-command> -> <script-path>.");
        #[cfg(feature = "trust-manifest")]
        example("  jao --ci --require-fingerprint <FINGERPRINT> test integrations myapp");
        #[cfg(not(feature = "trust-manifest"))]
        example("  jao --require-fingerprint <FINGERPRINT> test integrations myapp");
        line("    Run only if resolved script fingerprint matches exactly.");
        example("  jao test");
        line("    Run test.sh / test.bat if found.");
        example("  jao deploy api prod");
        line("    Run deploy.api.prod.sh / .bat if found.");
    } else {
        println!("jao - discover, inspect, and run workspace scripts");
        println!("  Finds platform scripts recursively and executes them from their own directory.");
        println!();
        println!("USAGE:");
        println!("  jao --list");
        println!("  jao --ci --list");
        println!("  jao --fingerprint <SCRIPT_COMMAND>...");
        println!("  jao <SCRIPT_COMMAND>...");
        #[cfg(feature = "trust-manifest")]
        println!("  jao --ci --require-fingerprint <FINGERPRINT> <SCRIPT_COMMAND>...");
        #[cfg(not(feature = "trust-manifest"))]
        println!("  jao --require-fingerprint <FINGERPRINT> <SCRIPT_COMMAND>...");
        println!();
        println!("OPTIONS:");
        option_plain("  -h, --help", "Show this help screen");
        option_plain("      --list", "List runnable scripts as command names plus their resolved file paths");
        option_plain(
            "      --fingerprint <SCRIPT_COMMAND>...",
            "Resolve a script command, then print SHA-256 of canonical path + file contents",
        );
        option_plain("      --ci", "Enable CI mode (non-interactive, no config/manifest I/O)");
        option_plain(
            "      --require-fingerprint <FINGERPRINT>",
            "Require exact script fingerprint before running",
        );
        option_plain("  -V, --version", "Print version");
        println!();
        println!("SCRIPT COMMAND INPUT:");
        println!("  Script file stems still use '.' as command separators.");
        println!("  Directories contribute command parts only when they contain a .jaofolder marker.");
        println!("  Example: myapp/backend/scripts/build.sh becomes:");
        println!("    jao myapp backend build from the workspace root if myapp/ and backend/ are marked");
        println!("    jao backend build from inside myapp/");
        println!("    jao build from inside backend/");
        println!("  Matching extension is chosen by OS: .sh on Unix-like systems, .bat on Windows.");
        println!("  The script runs with working directory set to the script's folder.");
        println!();
        println!("TRUST BEHAVIOR:");
        #[cfg(feature = "trust-manifest")]
        {
            println!("  Running a script requires trust.");
            println!("  Unknown scripts prompt: trust and run? [y/N]");
            println!("  Modified scripts prompt: re-trust and run? [y/N]");
            println!("  In non-interactive mode, unknown/modified scripts fail.");
            println!("  --list prints trust state labels plus command names and resolved paths.");
            println!("  --require-fingerprint can be used in CI mode.");
        }
        #[cfg(not(feature = "trust-manifest"))]
        {
            println!("  This build has trust-manifest disabled.");
            println!("  All runs require --require-fingerprint <FINGERPRINT>.");
            println!("  Runs are always non-interactive and never write trust state.");
            println!("  --list prints command names and resolved paths.");
        }
        println!("  --ci skips config/manifest creation and never prompts.");
        #[cfg(feature = "trust-manifest")]
        println!("  --ci run requires --require-fingerprint <FINGERPRINT>.");
        #[cfg(not(feature = "trust-manifest"))]
        println!("  --ci uses the same fingerprint-required run policy.");
        println!("  --ci --list prints command names and resolved paths (no trust labels).");
        println!();
        println!("EXAMPLES:");
        println!("  jao --fingerprint deploy api prod");
        println!("    Resolve deploy.api.prod.sh/.bat, then fingerprint that script file.");
        println!("  jao --list");
        #[cfg(feature = "trust-manifest")]
        println!("    Output format: <trust-state> <script-command> -> <script-path>.");
        #[cfg(not(feature = "trust-manifest"))]
        println!("    Output format: <script-command> -> <script-path>.");
        println!("  jao --ci --list");
        println!("    Output format: <script-command> -> <script-path>.");
        #[cfg(feature = "trust-manifest")]
        println!("  jao --ci --require-fingerprint <FINGERPRINT> test integrations myapp");
        #[cfg(not(feature = "trust-manifest"))]
        println!("  jao --require-fingerprint <FINGERPRINT> test integrations myapp");
        println!("    Run only if resolved script fingerprint matches exactly.");
        println!("  jao test");
        println!("    Run test.sh / test.bat if found.");
        println!("  jao deploy api prod");
        println!("    Run deploy.api.prod.sh / .bat if found.");
    }
}

fn should_style() -> bool {
    let no_color = std::env::var_os("NO_COLOR").is_some();
    let force_color = std::env::var("CLICOLOR_FORCE").ok().as_deref() == Some("1");
    (std::io::stdout().is_terminal() || force_color) && !no_color
}

fn section(name: &str) {
    println!("{BOLD}{UNDERLINE}{name}:{RESET}");
}

fn option(flag: &str, desc: &str) {
    if flag.chars().count() <= OPTION_COL_WIDTH {
        println!("{BOLD}{flag:<OPTION_COL_WIDTH$}{RESET}{desc}");
    } else {
        println!("{BOLD}{flag}{RESET}");
        println!("{OPTION_DESC_INDENT}{desc}");
    }
}

fn option_plain(flag: &str, desc: &str) {
    if flag.chars().count() <= OPTION_COL_WIDTH {
        println!("{flag:<OPTION_COL_WIDTH$}{desc}");
    } else {
        println!("{flag}");
        println!("{OPTION_DESC_INDENT}{desc}");
    }
}

fn line(text: &str) {
    println!("{text}");
}

fn example(cmd: &str) {
    println!("{GREEN}{cmd}{RESET}");
}
